apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: mth
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: abdurrahman11/nodejsapp:v2
        ports:
        - containerPort: 4000
        
